name: Continuous Integration

on:
  pull_request:
    branches: [master] # run on PRs opened against `main`

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Yarn Install
        run: yarn install --frozen-lockfile --ignore-scripts --non-interactive

      - name: Lint
        run: yarn lint

      - name: TypeScript Compilation
        run: yarn build
